/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GhostFaucetToken } from './GhostFaucetToken.js';
export type { GhostSendWrapper } from './GhostSendWrapper.js';
export * as factories from './factories/index.js';
export { GhostSendWrapper__factory } from './factories/GhostSendWrapper__factory.js';
export { GhostFaucetToken__factory } from './factories/GhostFaucetToken__factory.js';