/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GhostFaucetToken__factory } from './GhostFaucetToken__factory.js';
export { GhostSendWrapper__factory } from './GhostSendWrapper__factory.js';